{{- if .Values.ingress.enabled -}}
{{- $serviceName := .Values.appName -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $apiServiceName := .Values.ingress.backend.name -}}
{{- $apiServicePort := .Values.ingress.backend.port -}}
{{- $backendEnvName := .Values.ingress.env -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    kubernetes.io/ingress.class: nginx
  labels:
    app: {{ .Values.appName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          - path: /api/
            backend:
              serviceName: {{ $apiServiceName }}
              servicePort: {{ $apiServicePort }}
    {{- end -}}
  {{- end -}}